backend:
  name: git-gateway
  repo: bfuller7141/wvbe-test
  branch: main
  api_root: https://gitlab.com/api/v4

media_folder: static/images
public_folder: /images

collections:
  - name: 'events'
    label: 'Events'
    folder: 'content/events'
    create: true
    fields:
      - name: 'title'
        label: 'Event Name'
        widget: 'string'
        hint: ' Name of the event'
        required: true
        - { label: "Event Image", name: "image", widget: "image", required: true }
        - { label: "Event Category", name: "category", widget: "relation", collection: "categories", search_fields: ["title"], value_field: "title", display_fields: ["title"], required: true }
        - { label: "Event Title", name: "title", widget: "string", required: true }
        - { label: "Event Date", name: "date", widget: "datetime", required: true }
        - { label: "Event Time", name: "time", widget: "string", required: true }
        - { label: "Event Location", name: "location", widget: "string", required: true }
        - { label: "Event Price", name: "price", widget: "string", required: true }
        - { label: "Event Link", name: "link", widget: "string", required: true }
  -name: 'categories'
    label: 'Categories'
    folder: 'content/categories'
    create: true
    fields:
      - { label: "Category Title", name: "title", widget: "string", required: true }